// include/version.hpp
#pragma once
#define SIGHOUND_TRANSFER_VERSION "0.1.0"
#define SIGHOUND_TRANSFER_VERSION_MAJOR 0
#define SIGHOUND_TRANSFER_VERSION_MINOR 1
#define SIGHOUND_TRANSFER_VERSION_PATCH 0
